remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

# Opcional: Configurações extras do tema
theme: just-the-docs
collections:
  adr:
    output: true
    permalink: /:path/
