title: Documentação do Sistema
theme: just-the-docs
url: "https://multpex.github.io/docs"  # URL do GitHub Pages

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

collections:
  adr:
    output: true
    permalink: /:path/
    
